import type { Metadata } from "next";
import "@/app/globals.css";
import { SanityLive } from '@/sanity/lib/live'
import { Header } from "@/components/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
